//
// Created by Amr Hendy on 12/5/2018.
//

#ifndef TCP_PROTOCOL_CONSTANTS_H
#define TCP_PROTOCOL_CONSTANTS_H

#define CHUNK_SIZE 500
#define STOP_AND_WAIT_TIMEOUT 1
#define SR_TIMEOUT 1

#endif //TCP_PROTOCOL_CONSTANTS_H
